### PR TITLE
pipeline + components for rag x llamaindex

### PR DESCRIPTION
**Pull request by Hakimovich99**
Added components to have a "llama-index" pipeline where:
- the loaded data is chunked by creating Nodes
- the text is then embedded. Embeddings are stored in the "Nodes"
- Nodes are added to a vector store (weaviate_hakim)
Run "pipeline_li" to run the llama index pipeline.

Next step is to use the exact same pipeline as Matthias except that the chunks will be loaded in the Nodes format before being added to the vectorDB. A kind of "from Fondant to LlamaIndex" after doing the whole processing with "our own" components (chunk_text + embed_text).

### CODE REVIEW

**Comment by RobbeSneyders** [comment]
Thanks @Hakimovich99,

I would prefer to continue with the existing pipeline instead of having two pipelines. What are the benefits of this pipeline compared to the one already in the repository?

**Comment by Hakimovich99** [comment]
> Thanks @Hakimovich99,
> 
> I would prefer to continue with the existing pipeline instead of having two pipelines. What are the benefits of this pipeline compared to the one already in the repository?

As discussed during the standup, I'll now do a pipeline where I continue with the existing pipeline by adding a "from Fondant to LlamaIndex" component. I will make a third pipeline then, just to be able to compare them. 
The main benefit of these pipelines is simply that they incorporate LlamaIndex, something similar to what Ray did ([https://www.anyscale.com/blog/build-and-scale-a-powerful-query-engine-with-llamaindex-ray])

**Comment by RobbeSneyders** [comment]
We should really converge to a single pipeline. The goal should also be to have the best possible pipeline, and select the framework accordingly. I don't think using LlamaIndex everywhere is a prerequisite.

I see some downsides to using LlamaIndex due to their node structure, while I don't see advantages in a lot of components:
- In the chunking component, `LlamaIndex` just wraps a `LangChain` splitter, and returns nodes instead of chunks, which we then need to serialize again.
- In the embedding component, I don't see how `LlamaIndex` is easier than `LangChain`.

I think the nodes are mainly useful when they are stored in a vector store and `LlamaIndex` is used to query it. So maybe we only need to use `LlamaIndex` in the component that writes the data to the vector store.

**Comment by Hakimovich99** [comment]
> We should really converge to a single pipeline. The goal should also be to have the best possible pipeline, and select the framework accordingly. I don't think using LlamaIndex everywhere is a prerequisite.
> 
> I see some downsides to using LlamaIndex due to their node structure, while I don't see advantages in a lot of components:
> 
> * In the chunking component, `LlamaIndex` just wraps a `LangChain` splitter, and returns nodes instead of chunks, which we then need to serialize again.
> * In the embedding component, I don't see how `LlamaIndex` is easier than `LangChain`.
> 
> I think the nodes are mainly useful when they are stored in a vector store and `LlamaIndex` is used to query it. So maybe we only need to use `LlamaIndex` in the component that writes the data to the vector store.

Yep totally agree. The added value of LlamaIndex at the processing level is not a plus compared to other frameworks or so. But definitely at the storing and retrieval/query steps. I'll push a LlamaIndex component that writes the data to the vector store.

**Comment by RobbeSneyders** [comment]
Question then is if we can convert chunks into `LlamaIndex` `Nodes`, and if so, which data is needed for it.

**Comment by Hakimovich99** [comment]
I've pushed a pipeline where chunks are converted into LlamaIndex Nodes before being loaded to a vectorstore (see pipeline.py). The nodes contain the text and the embeddings. The main difference with the other approach (see pipeline_li.py), is the information gathered in the Nodes object at the end. 
Here is an example of the difference between both approach:
- in pipeline_li.py, we see that the Nodes contain "metadata" and "relationships" info. Which is useful to have a traceback to the original document id. I am still unsure of the added value of having those relationships but I think it can be useful in the retrieval part (with recursive retrieval for example)
image

- in pipeline.py, the Nodes content would limit to text and embedding. I think adding the metadata (if we have any) manually shouldn't be an issue. But it can be complicated when it comes to incorporating the "original_doc_id" (which is created in Philippe's chunking component) into the Nodes object under "relationships". Also, it would lead to re-doing a job that is already done by Llama-Index when creating Documents and Nodes object (relationships are automatically done). 
image

**Comment by Hakimovich99** [comment]
> I've pushed a pipeline where chunks are converted into LlamaIndex Nodes before being loaded to a vectorstore (see pipeline.py). The nodes contain the text and the embeddings. The main difference with the other approach (see pipeline_li.py), is the information gathered in the Nodes object at the end. Here is an example of the difference between both approach:
> 
> * in pipeline_li.py, we see that the Nodes contain "metadata" and "relationships" info. Which is useful to have a traceback to the original document id. I am still unsure of the added value of having those relationships but I think it can be useful in the retrieval part (with recursive retrieval for example)
> 
> image
> * in pipeline.py, the Nodes content would limit to text and embedding. I think adding the metadata (if we have any) manually shouldn't be an issue. But it can be complicated when it comes to incorporating the "original_doc_id" (which is created in Philippe's chunking component) into the Nodes object under "relationships". Also, it would lead to re-doing a job that is already done by Llama-Index when creating Documents and Nodes object (relationships are automatically done).
> 
> image

NB: there is a small error when running the pipeline.py script at the end of the last component. The Nodes are still well added to the vectorstore though, which is why I still pushed the code. I'm currently dealing with it with Matthias.

**Comment by RobbeSneyders** [comment]
> in pipeline_li.py, we see that the Nodes contain "metadata" and "relationships" info. Which is useful to have a traceback to the original document id. I am still unsure of the added value of having those relationships but I think it can be useful in the retrieval part (with recursive retrieval for example)

Agree, without these the nodes won't offer any benefit compared to loading without LlamaIndex.

Does LlamaIndex provide any benefits for the evaluation of the RAG setup compared to other frameworks?

**Comment by Hakimovich99** [comment]
> > in pipeline_li.py, we see that the Nodes contain "metadata" and "relationships" info. Which is useful to have a traceback to the original document id. I am still unsure of the added value of having those relationships but I think it can be useful in the retrieval part (with recursive retrieval for example)
> 
> Agree, without these the nodes won't offer any benefit compared to loading without LlamaIndex.
> 
> Does LlamaIndex provide any benefits for the evaluation of the RAG setup compared to other frameworks?

Concerning the evaluation of the RAG setup, according to how we've defined it with Bravo Squad, LlamaIndex don't provide any benefits because we basically just compare retrieved chunks with Ground Truth chunks based on the string ("Does the retrieved chunk contain text from the Ground Truth chunk?"). So any framework would do here.

**Comment by RobbeSneyders** [comment]
Let's close this for now and cherry pick useful changes for #10

**Pull request closed without merging**
