### PR TITLE
add evaluate retriever component + retriever component fix

### PR DESCRIPTION
**Pull request by Hakimovich99**
Fixed retriever component column names. Putting underscores create issues for the following component, swapped "_" with "+". Added retriever evaluation component with RAGAS. It requires an API key as an argument. Also added a (ugly) workaround in case some parquet files are empty.

### CODE REVIEW

**Comment by Hakimovich99** [comment]
Also @RobbeSneyders, regarding the last aggregate component. We already discussed it this morning but I was wondering, isn't it possible to create another dataset in another subset that we would call "agg results"? 
Because in this component here, the aggregate results are already computed (see screenshot). So can't we output a "text" subset that contains the dataframe with question, contexts, metrics, and another subset "agg results"? We can then compare different pipeline runs by comparing the "agg results" subset only. I'm not sure if we've discussed this specific idea already.
image

**Comment by RobbeSneyders** [comment]
All outputs of a component need to contain the same index. So it's not possible to output both of these in a single component.

**Comment by Hakimovich99** [comment]
Please don't merge yet, just noticed a few stuff to fix:)

**Review by RobbeSneyders — COMMENTED** [review]
Thanks @Hakimovich99,

- Can you add a test for the component?
- Currently we only support OpenAI, it would be great to let the user choose this.

**Comment by Hakimovich99** [comment]
> > Thanks @Hakimovich99,
> > 
> > * Can you add a test for the component?
> > * Currently we only support OpenAI, it would be great to let the user choose this.
> 
> Yes, I'll add a test!
> 
> Concerning OpenAI, I will check if I can make it easily tunable. However, RAGAS' default prompts cannot be modified. This means that results might not be relevant because the another LLM may not understand the task well. You can find them here (they've modified it recently btw) [https://github.com/explodinggradients/ragas/blob/9f22937c2834636f23176c402af2ec566435fe25/src/ragas/metrics/_context_precision.py](url)



> > Thanks @Hakimovich99,
> > 
> > * Can you add a test for the component?
> > * Currently we only support OpenAI, it would be great to let the user choose this.
> 
> Yes, I'll add a test!
> 
> Concerning OpenAI, I will check if I can make it easily tunable. However, RAGAS' default prompts cannot be modified. This means that results might not be relevant because the another LLM may not understand the task well. You can find them here (they've modified it recently btw) [https://github.com/explodinggradients/ragas/blob/9f22937c2834636f23176c402af2ec566435fe25/src/ragas/metrics/_context_precision.py](url)

@RobbeSneyders I took a look at how we could let the user choose the LLM. All LangChain LLMs can be used but the main problem is most models require API keys or URL which we must pass as argument since we cannot set environment variables within a component. But then, I don't know how we could pass both the import of the model and its arguments (which depend on the model, eg: for OpenAI it will be "openai_api_key" but for Cohere "cohere_api_key") directly in a component argument.
Do you know a way of dealing with that?

**Comment by RobbeSneyders** [comment]
I think there's two options:
- We "hardcode" the different options, similar to the `embed_text` component
- We add an `arguments` argument, which lets the user pass a dictionary of arguments to pass to the model. The content can be different for different models.

**Comment by Hakimovich99** [comment]
> I think there's two options:
> 
> * We "hardcode" the different options, similar to the `embed_text` component
> * We add an `arguments` argument, which lets the user pass a dictionary of arguments to pass to the model. The content can be different for different models.

I think there are too many LLMs so that we hardcode them

> I think there's two options:
> 
> * We "hardcode" the different options, similar to the `embed_text` component
> * We add an `arguments` argument, which lets the user pass a dictionary of arguments to pass to the model. The content can be different for different models.

I like the second option, I'll go for it, thanks!

**Pull request merged**
